### ISSUE TITLE
Leaflet-0.5.1 fails build with latest jshint@1.0.0

### ISSUE THREAD

**Issue by iger** [Leaflet/Leaflet#1493]
The lastest leaflet Leaflet-Leaflet-v0.5.1-0-gc1d410f.zip fails on checking source files with latest jshint@1.0.0 .

```
Checking for JS errors...
src/Leaflet.js  line 6  col 5    Redefinition of 'L'.
src/Leaflet.js  line 9  col 5    Read only.
src/Leaflet.js  line 12 col 5    Read only.
src/layer/vector/CircleMarker.js    line 19 col 1    Trailing whitespace.
4 error(s) found.

jake aborted.
Error
    at api.fail (/tmp/asdf/node_modules/jake/lib/api.js:235:13)
(See full trace by running task with --trace)
```

```
/tmp/asdf
├─┬ jake@0.5.8
│ ├─┬ minimatch@0.2.11
│ │ ├── lru-cache@2.2.2
│ │ └── sigmund@1.0.0
│ └── utilities@0.0.19
├─┬ jshint@1.0.0
│ ├─┬ cli@0.4.3
│ │ └─┬ glob@3.1.21
│ │   ├── graceful-fs@1.2.0
│ │   └── inherits@1.0.0
│ ├── esprima@1.1.0-dev
│ ├─┬ minimatch@0.2.11
│ │ ├── lru-cache@2.2.2
│ │ └── sigmund@1.0.0
│ ├── peakle@0.0.1
│ ├── shelljs@0.1.2
│ └── underscore@1.4.4
└─┬ uglify-js@2.2.5
  ├─┬ optimist@0.3.5
  │ └── wordwrap@0.0.2
  └─┬ source-map@0.1.9
    └── amdefine@0.0.4
```

If you need more information (e.g. leaflet builds for you), please specify.
