### ISSUE TITLE
How to substitute adjustTilePoint (_adjustTilePoint is not a function)

### ISSUE THREAD

**Issue by BaptWaels** [Leaflet/Leaflet#5103]
Hi, 

I'm using an [old lib](https://github.com/tilemapjp/mbtiles.js) to load a .mbtiles as a leaflet layer of my map. This lib is working fine with leaflet 0.7. The problem is when I use it with leaflet 1.0, I'm not able to retrieve the tileUrl because _adjustTilePoint was removed in leaflet v1.0

Working example of the lib with leaflet 0.7 and  _adjustTilePoint : http://jsfiddle.net/kochizufan/rj4Eh/

Any idea on how to substitute _adjustTilePoint and use leaflet 1.0 ?
Thank you

**Comment by perliedman** [comment]
Hi there,
this is more a question on how to use Leaflet, rather than an issue or feature suggestion. You might be better of asking on stackoverflow or https://gis.stackexchange.com.

Having said that, `TileLayer` has been heavily refactored, so there's no exact corresponding method in 1.0. You might want to look at `GridLayer`'s `_update`, `_addTile` and `_wrapCoords`, which have parts of the same logic, from a quick look at things.

**Comment by IvanSanchez** [comment]
I'm going to just leave this here: https://gitlab.com/IvanSanchez/Leaflet.TileLayer.MBTiles

**Comment by BaptWaels** [comment]
Thank you @perliedman and @IvanSanchez , it really helps.
