### ISSUE TITLE
Control removeFrom() method causes "is not a function" error [1.0.0-rc3]

### ISSUE THREAD

**Issue by snubian** [Leaflet/Leaflet#4868]
Since upgrading from Leaflet 0.7.7 to 1.0.0-rc3 I am getting `Uncaught TypeError: info.removeFrom is not a function`. The `info` in question is a [control](http://leafletjs.com/reference.html#control) to display some text. See [this JSFiddle](https://jsfiddle.net/snubian/gnzbss0z/) - the map is displayed and the `info` control added, but the `info.removeFrom(map)` fails with the above error.

If I fork the above JSFiddle and change the Leaflet version back to 0.7.7 then it runs fine ([working JSFiddle here](https://jsfiddle.net/snubian/24ed702y/)).

This occurs in several browsers I've tested (Chrome, Firefox, IE11).

**Comment by IvanSanchez** [comment]
If you check the API docs, you'll notice that the `L.Control.removeFrom()` method has been renamed into `L.Control.remove()`: http://leafletjs.com/reference-1.0.0.html#control-remove

So this is not a bug, but rather a manifestation of the breaking API changes between 0.7.x and 1.0.0.

**Comment by snubian** [comment]
Thank you @IvanSanchez - and my apologies, being somewhat new to Leaflet I wasn't aware of the separate updated docs for 1.0.

**Comment by IvanSanchez** [comment]
No big deal ;-)

**Comment by Chandra-Naik** [comment]
I am new to Leaflet, can anyone please help me : 
I am getting Uncaught TypeError: L.Control.Search is not a function
