### ISSUE TITLE
Add/remove events for L.LayerGroup/FeatureGroup/GeoJSON not working in v0.7.7

### ISSUE THREAD

**Issue by iH8** [Leaflet/Leaflet#4221]
Found this issue from two years ago, which has since been closed: https://github.com/Leaflet/Leaflet/issues/2462 The issuer never responded and Mourner closed it but i ran into the same problem today when helping someone out on Stackoverflow. I thought posting a new issue was best since i'm not sure if somebody is actively reading comments on closed issues. If i'm wrong sorry in advance.

Case in point:

    var layerGroup = new L.LayerGroup();
    
    layerGroup.on('add', function () {
        console.log('Layergroup added!');
    });
    
    layerGroup.addTo(map);
    
    layerGroup.on('remove', function () {
        console.log('Layergroup removed!');
    });
    
    layerGroup.remove();

In 0.7.7 throws the following error:

>Uncaught TypeError: layerGroup.on is not a function

http://plnkr.co/edit/9LHvlcKfnhcPW8ldwPc2?p=preview

In 1.0.0-beta.2 everything's just fine:

>Layergroup added!
>Layergroup removed!

http://plnkr.co/edit/0JPMZRUKJRZ5xqvKOLuG?p=preview

Seems like a bug to me but i could be wrong and doing some dumb like i do once in a while. ;) If so, my apologies in advance. 

EDIT: Confused as i am, just realized that no events should be functioning since `on` isn't recognized and wanted to note that i'm assuming that FeatureGroup/GeoJSON don't work too because they're extended from LayerGroup but i didn't go as far as actually test that. Just want some preliminary feedback, if i'm correct and if so, if i can do anything to help out further, please holler.

**Comment by IvanSanchez** [comment]
> Uncaught TypeError: layerGroup.on is not a function

In 0.7.x, `L.LayerGroup` does **not** implement the event methods. If you need to use events with layer groups in 0.7.x, use `L.FeatureGroup` instead.

Implementing events in `L.LayerGroup` for 0.7.x is simply too much work, and the team agreed to not implement any new features but do only maintenance on big (critical) bugs.

> layerGroup.remove();

Also, `L.LayerGroup` and `L.FeatureGroup` do not implement the `remove()` method in 0.7.x

> I could be wrong and doing some dumb

Nah, I think this is half "the user didn't really paid close attention to the documentation" and half "requesting a new feature for the `stable` branch that won't be implemented" ;-)

**Comment by iH8** [comment]
Ok point taken, thanks for the clarification.
