### ISSUE TITLE
L.Map.fitBounds() with invalid bounds error message could be better

### ISSUE THREAD

**Issue by Jonas-WMDE** [Leaflet/Leaflet#4345]
`Uncaught TypeError: Cannot read property 'lat' of undefinedo.LatLngBounds.getNorth @ leaflet.js:6o.LatLngBounds.getNorthWest @ leaflet.js:6o.Map.o.Class.extend.getBoundsZoom @ leaflet.js:6o.Map.o.Class.extend.fitBounds @ leaflet.js:6wikibase.queryService.ui.resultBrowser.CoordinateResultBrowser.SELF.draw @ CoordinateResultBrowser.js:64(anonymous function) @ App.js:411`

http://tinyurl.com/jbxrwlv

**Comment by IvanSanchez** [comment]
Maybe a check for `bounds.isValid()` inside `fitBounds()` is a good idea (throw a descriptive error if not). Otherwise, `isValid()` can be called from the user's code.

**Comment by IvanSanchez** [comment]
Maybe this bug report is a good candidate for @yourfirstpr ?

Code-wise, the changes are simple (inside the `fitBounds` method in `L.Map`, check if the bounds are valid with a call to `bounds.isValid()`, then throw an error in the same way `_initContainer` does. 

Other than that, it's the usual "claim the issue, fork, clone, branch, edit, commit, pull request" workflow.

**Comment by theotow** [comment]
i will give it a try

**Comment by IvanSanchez** [comment]
Closed via #4353

**Comment by renandegrandi** [comment]
Formerly the fitBounds () function could receive an array of markers.
With this the validation:
`bounds =  L.latLngBounds(bounds);`

Will always be invalid.

But within the call:
`_getBoundsCenterZoom: function (bounds, options) {`

Is validated as follows the bounds.
`bounds = bounds.getBounds ? bounds.getBounds() : L.latLngBounds(bounds);`

I made some tests here and to stop the errors in the new version the validation should be as follows:

```
	fitBounds: function (bounds, options) {

	    bounds = bounds.getBounds ? bounds.getBounds() : L.latLngBounds(bounds);

		if (!bounds.isValid()) {
			throw new Error('Bounds are not valid.');
		}

		var target = this._getBoundsCenterZoom(bounds, options);
		return this.setView(target.center, target.zoom, options);
	},
```

**Comment by ghybs** [comment]
Hi,

It is true that it is strange to perform a sanity check (introduced by PR https://github.com/Leaflet/Leaflet/pull/4353) before [`_getBoundsCenterZoom`](https://github.com/Leaflet/Leaflet/blob/v1.0.3/src/map/Map.js#L234-L256), which does its own conversion to `LatLngBounds` and even accepts an object with `getBounds` method (e.g. a [Feature Group](http://leafletjs.com/reference-1.0.3.html#featuregroup-getbounds), an [Image Overlay](http://leafletjs.com/reference-1.0.3.html#imageoverlay-getbounds), a [Polyline](http://leafletjs.com/reference-1.0.3.html#polyline-getbounds) / Polygon / Rectangle, or a [Circle](http://leafletjs.com/reference-1.0.3.html#circle-getbounds)), even though this is not documented in the public API.

The preceding conversion to LatLngBounds (introduced by PR https://github.com/Leaflet/Leaflet/pull/4375) is similarly strange, since it duplicates this conversion, while being less permissive.

Finally, [`flyToBounds`](http://leafletjs.com/reference-1.0.3.html#map-flytobounds) also makes use of `_getBoundsCenterZoom` but does not implement those 2 modifications, which is inconsistent.

Therefore it seems to me that if this were to be changed, it would be more consistent to implement the sanity check directly within `_getBoundsCenterZoom`, so that all public methods that use it can benefit, and it also avoids the double / less permissive conversion.

That being said, I do not see how any of this code can work with an array of markers.
Were you referring to a Feature Group?

**Comment by renandegrandi** [comment]
@ghybs  Yes, you're correct I was referencing for an object of L.featureGroup.

**Comment by andrzej-wisla** [comment]
Uncaught Error: fitBounds: latLngBounds must be of type LatLngBounds.
What does it means ?
